w3c/hr-time

index.html

Addresses
https://github.com/w3c/navigation-timing/issues/22#issuecomment-121989555

Added a serializer on performance objects

---

index.html

Addresses https://github.com/w3c/hr-time/issues/16
Unless I hear otherwise, I'll merge this one by tomorrow.

Updated the status. translateTime is @ risk

---

index.html

translateTime was already marked as at risk and will be replaced by
timeOrigin (or some variant of it, once we iron out the details) in
Level 3. Despite the absence of this mechanism in L2, the developers can
still do one of the following:
- Translate high-resolution timestamps to Date objects, which will offer
millisecond level resolution, if they need to be mapped into same
timeline.
- Communicate high-resolution timestamps, or their deltas, across
contexts if they do not need to be mapped into same time origin.

remove translateTime from Level 2

---

index.html

Closes #44.
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/hr-time/now-primitive.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/hr-time/7d8d194...466529c.html)

Define "current high resolution time" as primitive

---

README.md
W3CTRMANIFEST
index.html
w3c.json

Per discussion in [1], merging timeOrigin back into Level 2 and dropping
Level 3. We'll need to republish new CR.
[1]
https://lists.w3.org/Archives/Public/public-web-perf/2017Jul/0010.html
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/hr-time/l2.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/hr-time/0adb0b4...6813781.html)

Merge timeOrigin into Level 2

---

index.html

The broken example causes the highlight script to completely screw it up.
So it currently looks like this:
***
[Preview](https://s3.amazonaws.com/pr-preview/ericduran/hr-time/fix-broken-example.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/hr-time/179cbb1...ericduran:7833dc3.html)

Example currently broken in latest/published versions

---

index.html

This PR addresses an ambiguity in the spec regarding the time origin during an `onunload` event.  Chart for reference:
At `Cu`, the spec as-written can be interpreted in one of two ways.  The time origin could either be `Cp` or `Bp` (or `Ap`, really).  The browser implementations use `Bp` as the time-origin.
The changes made to the spec disambiguates this case, as well as for measurements taken at `Bu` and `Au`, although the ambiguity has slightly different implications in those cases.  The new text indicates that the _previous document's_ prompt confirmation time should be used as the time origin, if available.  Otherwise it falls back to the next condition in the spec.
I'll be following up by adding tests in the https://github.com/w3c/web-platform-tests repo.
***
<a …

Update spec to fix ambiguity around Time Origin definition.

---

index.html

Temporary warning while #56 is being sorted out.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/57.html" title="Last updated on Feb 28, 2018, 2:25 PM GMT (c5f5407)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/57/05f4c00...c5f5407.html" title="Last updated on Feb 28, 2018, 2:25 PM GMT (c5f5407)">Diff</a>

Add a note regarding HRT precision

---

index.html

...and so extensions should use [`partial interface mixin`](https://heycam.github.io/webidl/#partial-interface-mixin) rather than `interface mixin`.
See also https://github.com/whatwg/html/pull/3650
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/hr-time/pull/58.html" title="Last updated on Apr 27, 2018, 11:45 AM GMT (9edbcf7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/58/5220e4b...saschanaz:9edbcf7.html" title="Last updated on Apr 27, 2018, 11:45 AM GMT (9edbcf7)">Diff</a>

WindowOrWorkerGlobalScope is a mixin

---

index.html

Refer to ECMA-262 time rather than unix time

---

index.html

Based on @tomrittervg's [comment](https://github.com/w3c/hr-time/issues/64#issuecomment-486760572).
Closes #67
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/hr-time/pull/68.html" title="Last updated on May 7, 2019, 3:46 PM UTC (bcbc9aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/68/f7f3537...yoavweiss:bcbc9aa.html" title="Last updated on May 7, 2019, 3:46 PM UTC (bcbc9aa)">Diff</a>

Added a list of potential mitigations to timing attacks

---

index.html

Closes #65
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/hr-time/pull/69.html" title="Last updated on May 14, 2019, 9:36 PM UTC (02bcea5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/69/c0bcbc2...yoavweiss:02bcea5.html" title="Last updated on May 14, 2019, 9:36 PM UTC (02bcea5)">Diff</a>

Add a note on now() in backgrounded tabs

---

index.html

This improves our definitions, following Marcos input. There are still some definitions that I can't reach without a data-cite but that will be for another day.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/72.html" title="Last updated on Jun 26, 2019, 2:44 PM UTC (af71971)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/72/0e75011...af71971.html" title="Last updated on Jun 26, 2019, 2:44 PM UTC (af71971)">Diff</a>

Adding export, no-export, and improving some refs

---

index.html

Otherwise, it's breaking the linking in the bibliography.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/73.html" title="Last updated on Jun 27, 2019, 5:24 AM UTC (eac246f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/73/2af995b...eac246f.html" title="Last updated on Jun 27, 2019, 5:24 AM UTC (eac246f)">Diff</a>

Editorial: give SPECTRE paper a title

---

index.html

Closes #77 by adding sections and headings. 
Adds idl-index at end, so API is easy to see. 
Moved conformance to bottom of spec. 
Tidy'd up markup.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/78.html" title="Last updated on Jul 1, 2019, 12:23 AM UTC (d6687c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/78/98557e8...d6687c9.html" title="Last updated on Jul 1, 2019, 12:23 AM UTC (d6687c9)">Diff</a>

Editorial: add headings/sections

---

index.html

- Spell out the recommended 5 microsecond minimum (tested)
- Updated note to link to #79 to track ongoing research
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/80.html" title="Last updated on Jul 2, 2019, 9:26 PM UTC (6673965)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/80/371b114...6673965.html" title="Last updated on Jul 2, 2019, 9:26 PM UTC (6673965)">Diff</a>

update clock resolution recommendation + reference

---

errata.html
index.html

* Remove Level number from ED
* clear SOTD
* Add errata page if we end up using one in the future
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/85.html" title="Last updated on Nov 20, 2019, 4:12 PM UTC (15015d5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/85/290614f...15015d5.html" title="Last updated on Nov 20, 2019, 4:12 PM UTC (15015d5)">Diff</a>

Prep for upcoming

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/86.html" title="Last updated on Dec 30, 2019, 2:32 PM UTC (36d10ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/86/f56f3c3...36d10ac.html" title="Last updated on Dec 30, 2019, 2:32 PM UTC (36d10ac)">Diff</a>

chore: remove ReSpec format option, spec uses HTML

---

index.html

Fixes https://github.com/w3c/hr-time/issues/90
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/91.html" title="Last updated on May 6, 2020, 3:37 PM UTC (fda1639)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/91/c3ffb06...fda1639.html" title="Last updated on May 6, 2020, 3:37 PM UTC (fda1639)">Diff</a>

Export DOMHighResTimeStamp

---

index.html

Fixes https://github.com/w3c/hr-time/issues/87 by defining the concept of **relative high resolution time** .
Capable of being exported
***
<a href="https://pr-preview.s3.amazonaws.com/igneel64/hr-time/pull/95.html" title="Last updated on Sep 16, 2020, 6:57 AM UTC (c376f39)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/95/c2cb506...igneel64:c376f39.html" title="Last updated on Sep 16, 2020, 6:57 AM UTC (c376f39)">Diff</a>

Define 'relative high resolution time'

---

index.html

- Fixes https://github.com/w3c/hr-time/issues/96
Definition based on https://infra.spec.whatwg.org/ spec & reform 'current high resolution time' to accept a global argument
***
<a href="https://pr-preview.s3.amazonaws.com/igneel64/hr-time/pull/97.html" title="Last updated on Sep 22, 2020, 3:43 PM UTC (1f4f6cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/97/f563a5f...igneel64:1f4f6cd.html" title="Last updated on Sep 22, 2020, 3:43 PM UTC (1f4f6cd)">Diff</a>

Correct algorithm definition & 'current high resolution time' reform - Fixes #96

---

index.html

Closes #89 
We still need to discuss and see what `X` value would be reasonable here
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/hr-time/pull/93.html" title="Last updated on Feb 18, 2021, 11:01 AM UTC (944206a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/93/9b17e2b...yoavweiss:944206a.html" title="Last updated on Feb 18, 2021, 11:01 AM UTC (944206a)">Diff</a>

Limit the timer resolution in non-isolated contexts

---

index.html

"global" is a term already used to describe the global
object, while this monotonic clock is shared across globals
(e.g. workers and the window).
Also expose "unsafe shared current time", for use by Fetch.
See https://github.com/whatwg/fetch/pull/1185
Closes https://github.com/w3c/hr-time/issues/99
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/107.html" title="Last updated on Mar 4, 2021, 7:42 AM UTC (4b53a3b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/107/f58edac...4b53a3b.html" title="Last updated on Mar 4, 2021, 7:42 AM UTC (4b53a3b)">Diff</a>

Change "global monotonic clock" to "shared" and expose new algorithm "unsafe shared current time"

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/hr-time/pull/109.html" title="Last updated on Mar 9, 2021, 8:52 AM UTC (a584bc3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/109/669b4f4...yoavweiss:a584bc3.html" title="Last updated on Mar 9, 2021, 8:52 AM UTC (a584bc3)">Diff</a>

Fix reference to unsafe shared time

---

index.html

This PR does multiple things:
* It splits out timestamp coarsing into its own algorithm, as it's needed in multiple places
* It coarsens the value returned "time origin timestamp" and hence from `performance.timeOrigin`
* It changes the relative high resolution time definition to use "time origin timestamp" and hence to be coarsed, compared to the current algorithm which uses "time origin" directly (since "time origin" is a point in time, rather than a timestamp, it's unclear what the current diffing means, and "time origin timestamp" seems like a more appropriate value)
/cc @annevk
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/hr-time/pull/106.html" title="Last updated on Mar 9, 2021, 8:04 PM UTC (dbbe2ce)">Preview</a> | <a …

Coarsen timeOrigin

---

index.html

Followup from #106, this makes sure that calling "relative HR time" is properly coarsened and safe to expose.
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/hr-time/pull/111.html" title="Last updated on Mar 10, 2021, 6:07 AM UTC (9c80718)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/111/29866ae...yoavweiss:9c80718.html" title="Last updated on Mar 10, 2021, 6:07 AM UTC (9c80718)">Diff</a>

Coarsen relative time

---

index.html

Fetch needs to obtain time values from in parallel and would like to avoid having to store raw time values and hand these over to "attacker" agent clusters.
I also changed some unordered lists to ordered lists as they are sequences of steps.
(As discussed in https://github.com/w3c/resource-timing/pull/261.)
***
<a href="https://pr-preview.s3.amazonaws.com/annevk/hr-time/pull/112.html" title="Last updated on Mar 19, 2021, 11:31 AM UTC (1b751b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/112/5df6272...annevk:1b751b3.html" title="Last updated on Mar 19, 2021, 11:31 AM UTC (1b751b3)">Diff</a>

Add coarsened shared current time

---

index.html

For resource-timing, we pre-coarsen the timestamps before
they can be converted to relative timestamps, so the inermediate
algorithm to calculate the relative timestamp from a pre-coarsened
absolulte timestamp is needed.
See https://github.com/w3c/resource-timing/pull/261
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/114.html" title="Last updated on Mar 25, 2021, 3:30 PM UTC (5cee397)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/114/4680852...5cee397.html" title="Last updated on Mar 25, 2021, 3:30 PM UTC (5cee397)">Diff</a>

Expose "relative high resolution coarse time"

---

index.html

Replaces `context object` with `this`, and while at it also fixes the mdn reference.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/116.html" title="Last updated on May 6, 2021, 9:12 PM UTC (f796db1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/116/b6cbe47...f796db1.html" title="Last updated on May 6, 2021, 9:12 PM UTC (f796db1)">Diff</a>

Remove context object usage

---

.github/workflows/tidy.yml
index.html
tidyconfig.txt

This workflow will automatically tidy up documents _after_ a pull request is merged, and it sends a pull request if was fixed by tidy. 
This allows folks to make contributions without needing to worry *too much* about the markup they are writing.
@yoavweiss, 99% tidy will do the right thing. However, if a contribution has garbage HTML (e..g, `<section>` is not closed), tidy will try to recover. In such cases, please double check that tidy has done what we want. 
Any issues, just ping!
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/118.html" title="Last updated on Jun 7, 2021, 5:51 AM UTC (c8d0473)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/118/94f3eb5...c8d0473.html" title="Last updated on Jun 7, 2021, 5:51 AM UTC (c8d0473)">Diff</a>

chore: automatic tidy

---

index.html

See https://github.com/whatwg/html/pull/7339
`time origin` is now an `environment settings object` algorithm,
so the reference here should forward there.
Closes #131
Person merging, please make sure that commits are squashed with one of the following as a commit message prefix:
- chore: fixes unrelated to the spec itself (e.g., fix to Github action, html tidy, spec config, etc.). 
- editorial: a non-normative change to the spec (e.g., fixing an example or typo, adding a note).
- change: a normative change to existing engine behavior.
- And use none if it's a new normative requirement. 
If this is a "change", please explain what's significantly changing. 
In particular, if the change results in potential backwards compatibility issues and content breakage, it needs to be justified.
For …

Remove own version of `timeOrigin` definition

---

index.html

Add a note about cross-origin information and the document's time origin.
This fixes the lint warning which expects separate privacy/security sections.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/134.html" title="Last updated on Jan 17, 2022, 12:38 PM UTC (d7f89b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/134/1029373...d7f89b5.html" title="Last updated on Jan 17, 2022, 12:38 PM UTC (d7f89b5)">Diff</a>

Add a privacy section

---

index.html

Reverts w3c/hr-time#130 given discussion on https://w3c.github.io/web-performance/meetings/2022/2022-06-23/index.html#h.1of8nktf4mlh
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/138.html" title="Last updated on Jul 22, 2022, 2:01 PM UTC (639ddf6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/138/e7285a2...639ddf6.html" title="Last updated on Jul 22, 2022, 2:01 PM UTC (639ddf6)">Diff</a>

Revert "Expose everywhere"

---

index.html

I believe this fixes #139.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/hr-time/pull/140.html" title="Last updated on Jan 12, 2023, 3:15 PM UTC (2c194b4)">Preview</a> (<a href="https://pr-preview.s3.amazonaws.com/jyasskin/hr-time/pull/140.html#sec-concepts" title="#sec-concepts">#sec-…</a>) (<a href="https://pr-preview.s3.amazonaws.com/jyasskin/hr-time/pull/140.html#sec-tools" title="#sec-tools">#sec-…</a>) (<a href="https://pr-preview.s3.amazonaws.com/jyasskin/hr-time/pull/140.html#sec-time-origin" title="#sec-time-origin">#sec-…</a>) (<a href="https://pr-preview.s3.amazonaws.com/jyasskin/hr-time/pull/140.html#sec-domhighrestimestamp" title="#sec-domhighrestimestamp">#sec-…</a>) (<a href="https://pr-preview.s3.amazonaws.com/jyasskin/hr-time/pull/140.html#the-epochtimestamp-ty …

editorial: Introduce clocks, moments, and durations

---

index.html

Or else subtracting durations that share a coarse endpoint winds up
revealing the precise difference between other endpoints, which can
build a high-precision timer.
This winds up requiring that we coarsen the estimated monotonic epoch
time, for type compatibility. With low confidence, I think it's
unobservable whether implementations actually do that...
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/hr-time/pull/144.html" title="Last updated on Jan 12, 2023, 6:00 PM UTC (f0a1dcf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/144/f3b6080...jyasskin:f0a1dcf.html" title="Last updated on Jan 12, 2023, 6:00 PM UTC (f0a1dcf)">Diff</a>

Durations actually need to have both endpoints coarsened.

---

index.html

@xyaoinum, does this text help explain what to do with https://github.com/patcg-individual-drafts/topics/pull/93#discussion_r1096846383? There's no implicit "time origin" for moments, so it's not right to assign one to a [DOMHighResTimeStamp](https://w3c.github.io/hr-time/#dom-domhighrestimestamp). Section 3 discusses what to do instead: do you think this text should link directly there?
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/hr-time/pull/147.html#moments-and-durations" title="Last updated on Feb 7, 2023, 5:51 PM UTC (704622a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/147/4a67828...jyasskin:704622a.html" title="Last updated on Feb 7, 2023, 5:51 PM UTC (704622a)">Diff</a>

editorial: Try to explain moments better.

---

index.html

Closes #149
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/150.html" title="Last updated on Feb 16, 2023, 10:49 AM UTC (9f7d9a8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/150/e7285a2...9f7d9a8.html" title="Last updated on Feb 16, 2023, 10:49 AM UTC (9f7d9a8)">Diff</a>

Editorial: Add note about DOMHighResTimestamp precision

---

index.html

It was ambiguous about whether it rounded to the nearest integer, and new specifications should use the terms in #sec-tools instead.
https://github.com/whatwg/notifications/pull/192 removes the only use listed in https://dontcallmedom.github.io/webdex/e.html#epoch-relative%20timestamp%40%40hr-time%25%25dfn. If I missed another one, whoever cleans that up can imitate the replacement in that PR or in the #the-epochtimestamp-typedef section here.
----
Person merging, please make sure that commits are squashed with one of the following as a commit message prefix:
- chore: fixes unrelated to the spec itself (e.g., fix to Github action, html tidy, spec config, etc.). 
- editorial: a non-normative change to the spec (e.g., fixing an example or typo, adding a note).
- change: a normative change …

editorial: Remove the definition of "epoch-relative timestamp".

---

index.html

Closes #156
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/157.html" title="Last updated on Apr 5, 2023, 6:10 AM UTC (8c695d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/157/04c6a92...8c695d4.html" title="Last updated on Apr 5, 2023, 6:10 AM UTC (8c695d4)">Diff</a>

Editorial: Add ids to unsafe-current-time dfns

---

index.html

Closes #155
Person merging, please make sure that commits are squashed with one of the following as a commit message prefix:
- chore: fixes unrelated to the spec itself (e.g., fix to Github action, html tidy, spec config, etc.). 
- editorial: a non-normative change to the spec (e.g., fixing an example or typo, adding a note).
- change: a normative change to existing engine behavior.
- And use none if it's a new normative requirement.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/hr-time/pull/161.html#dfn-current-wall-time" title="Last updated on Apr 24, 2023, 5:56 PM UTC (38b9302)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/161/bf43e1e...jyasskin:38b9302.html" title="Last updated on Apr 24, 2023, 5:56 PM UTC (38b9302)">Diff</a>

editorial: Add a definition for the "current wall time" without a settings object.

---

index.html

Closes #165
This is a non-functional change, to enable distinguishing between the Environment Settings Object's "current wall time" and the equivalent concept that can be used without one.
No implementation commitment or tests are needed.
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/hr-time/pull/167.html" title="Last updated on Nov 7, 2024, 10:40 AM UTC (61fa53d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/167/8558f93...yoavweiss:61fa53d.html" title="Last updated on Nov 7, 2024, 10:40 AM UTC (61fa53d)">Diff</a>

Rename one of the "current wall time" dfns
