w3c/hr-time

- index.html
Closes #1. 
ML discussion: https://lists.w3.org/Archives/Public/public-web-perf/2015Feb/0070.html
> Consistent time origin for Shared+Dedicated workers

- index.html
Also addresses
https://lists.w3.org/Archives/Public/public-web-perf/2015Jun/0081.html
> respec and moving the base interface

- index.html
Some suggested improvements for time origin
> Improve translateTime description and clarify monotonic clock section

- index.html
> Clamp resolution to 5 microseconds

- index.html
> Security consequences of exposing time measurement

- index.html
> Service worker reference isn't needed

- index.html
Closes https://github.com/w3c/hr-time/issues/36.
> clarify timeOrigin timestamp

- index.html
Minor cleanup
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/hr-time/respec-errors-cleanup.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/hr-time/f84f6ee...f8f20c7.html)
> Remove one error and several respec warnings

- CONTRIBUTING.md
- README.md
See
https://lists.w3.org/Archives/Public/public-web-perf/2017Mar/0023.html
https://lists.w3.org/Archives/Public/public-web-perf/2017May/0003.html
Also attempting to reuse https://w3c.github.io/spec-labels.html
@foolip @yoavweiss
> Test driven

- index.html
to fix #46
***
[Preview](https://s3.amazonaws.com/pr-preview/siusin/hr-time/update-workers-refs.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/hr-time/f8602d5...siusin:0912d46.html)
> Update workers refs

- index.html
use data-cite, data-tests, and data-number
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/53.html" title="Last updated on Dec 20, 2017, 5:15 AM GMT (4ff03b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/53/88792cc...4ff03b5.html" title="Last updated on Dec 20, 2017, 5:15 AM GMT (4ff03b5)">Diff</a>
> Harmonized links and references, adding links to tests and issues

- index.html
Editors, reviewers, and wg members, I would kindly ask that you perhaps put in place a some means to double check your references before merging pull requests. This can be as simple as just using a Github [pull request template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) with a checkbox that someone has done this. 
Also, please try to be precise with what you reference. For instance, this spec tried to reference "dedicated workers" and "shared workers", which are not actual concepts in HTML (those are non-normative concepts used in examples and tutorials). Those concepts are actually represented by IDL interfaces, which is what you actually want to reference. 
Please also try to make more extensive use of HTML5 tidy before merging:
```
tidy …
```
> Editorial: fix cross refs, tidy up

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/63.html" title="Last updated on Nov 7, 2018, 12:53 PM GMT (c36c5f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/63/2337b4c...c36c5f9.html" title="Last updated on Nov 7, 2018, 12:53 PM GMT (c36c5f9)">Diff</a>
> editorial: tidy + remove inline markdown

- index.html
Updates for former editors
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/70.html" title="Last updated on May 29, 2019, 2:43 PM UTC (e6d4d40)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/70/5e2084b...e6d4d40.html" title="Last updated on May 29, 2019, 2:43 PM UTC (e6d4d40)">Diff</a>
> Refreshed ReSpec config

- index.html
Defines EventHandler and improve WebIDL linking
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/71.html" title="Last updated on Jun 6, 2019, 11:14 AM UTC (ab5cf24)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/71/5e2084b...ab5cf24.html" title="Last updated on Jun 6, 2019, 11:14 AM UTC (ab5cf24)">Diff</a>
> Fixed respec references

- index.html
fixes #83 ... note that IDL things are treated as case sensitive.. so s/performance/Performance :)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/84.html" title="Last updated on Oct 16, 2019, 8:07 AM UTC (8d58fd6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/84/2290ca4...8d58fd6.html" title="Last updated on Oct 16, 2019, 8:07 AM UTC (8d58fd6)">Diff</a>
> chore: xref fixes

- index.html
This PR includes a few changes to fix some minor editorial issues I found during my AC review, which hopefully help readability. (Should be non-substantive for IPR.)
***
<a href="https://pr-preview.s3.amazonaws.com/chrisn/hr-time/pull/82.html" title="Last updated on Oct 21, 2019, 8:53 AM UTC (c42d3e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/82/d20fcf7...chrisn:c42d3e5.html" title="Last updated on Oct 21, 2019, 8:53 AM UTC (c42d3e5)">Diff</a>
> Some minor editorial changes

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/sidvishnoi/hr-time/pull/92.html" title="Last updated on Jul 10, 2020, 2:29 PM UTC (29ee6c1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/92/a50d0f1...sidvishnoi:29ee6c1.html" title="Last updated on Jul 10, 2020, 2:29 PM UTC (29ee6c1)">Diff</a>
> chore: fix ReSpec related errors

- .travis.yml
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/98.html" title="Last updated on Oct 1, 2020, 12:23 PM UTC (af8af70)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/98/9b17e2b...af8af70.html" title="Last updated on Oct 1, 2020, 12:23 PM UTC (af8af70)">Diff</a>
> Upgraded config for automatic publishing

- index.html
Closes #101
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/hr-time/pull/103.html" title="Last updated on Feb 12, 2021, 4:00 PM UTC (4e51ea8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/103/9b17e2b...yoavweiss:4e51ea8.html" title="Last updated on Feb 12, 2021, 4:00 PM UTC (4e51ea8)">Diff</a>
> Add a use cases section

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/annevk/hr-time/pull/113.html" title="Last updated on Mar 24, 2021, 10:41 AM UTC (285a039)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/113/06d54e6...annevk:285a039.html" title="Last updated on Mar 24, 2021, 10:41 AM UTC (285a039)">Diff</a>
> Meta: export coarsen time for Fetch

- index.html
Depends on https://github.com/tobie/specref/pull/667
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/117.html" title="Last updated on Jun 7, 2021, 5:45 AM UTC (42c7d61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/117/8d554fe...42c7d61.html" title="Last updated on Jun 7, 2021, 5:45 AM UTC (42c7d61)">Diff</a>
> chore: cleanup config

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/122.html" title="Last updated on Jul 15, 2021, 3:28 AM UTC (fd78b2a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/122/853843c...fd78b2a.html" title="Last updated on Jul 15, 2021, 3:28 AM UTC (fd78b2a)">Diff</a>
> Editorial: remove merge garbage from example

- index.html
Minor fixups after #140.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/hr-time/pull/143.html" title="Last updated on Jan 12, 2023, 5:46 PM UTC (93e4f94)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/143/f3b6080...jyasskin:93e4f94.html" title="Last updated on Jan 12, 2023, 5:46 PM UTC (93e4f94)">Diff</a>
> editorial: Use Respec's variable typing, and use the duration-from algorithm.

- index.html
Closes #152
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/pull/159.html" title="Last updated on Apr 11, 2023, 11:36 AM UTC (9c25b5c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/159/e27fb09...9c25b5c.html" title="Last updated on Apr 11, 2023, 11:36 AM UTC (9c25b5c)">Diff</a>
> Editorial: performance.now(): Use relevant global object

- index.html
This makes it easier to see all the terms that this specification defines.
***
<a href="https://pr-preview.s3.amazonaws.com/rakuco/hr-time/pull/163.html" title="Last updated on Jul 19, 2023, 12:31 PM UTC (41973f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/hr-time/163/a7f93e9...rakuco:41973f5.html" title="Last updated on Jul 19, 2023, 12:31 PM UTC (41973f5)">Diff</a>
> Editorial: Add an index to the appendices
